### ISSUE TITLE
PM: CPU Idle doesn't work on Armada 38x

### ISSUE THREAD

**Issue by gclement** [MISL-EBU-System-SW/mainline-public#62] opened 2015-03-30 12:29 UTC
Under some circumstance (PCIe related  but not only), kernel hangs when CPU idle is enabled.

**Comment by tpetazzoni** [comment] 2015-05-23 07:21
Gregory, isn't this bug "fixed" now that we have completely disabled cpuidle on Armada 38x?

**Comment by gclement** [comment] 2015-05-25 15:52
I would like to have a proper solution for this bug. Either completely removing CPU Idle if it does not work at all, or being able to enable for some configuration. The best solution would be to find a fix or a work around.

**Comment by stsp** [comment] 2015-05-26 10:07
Why is this not a problem with armada-XP?
I am pretty sure I have that on armada-XP,
but only in DEEP_IDLE state.

This patch:
http://lkml.iu.edu/hypermail/linux/kernel/1503.1/05016.html
prevents entering DEEP_IDLE, and the problem
no longer appears. Is it the same on Armada 38x?

**Comment by tpetazzoni** [comment] 2015-06-10 08:20
@stsp No, the problem shouldn't appear on Armada XP. Armada XP uses the PJ4B-MP CPU core, while Armada 38x uses Cortex-A9. The specific reason why cpuidle is problematic on Armada 38x is because when HW I/O coherency is enabled, we are not allowed to do PL310 maintenance operations through MMIO registers due to a HW deadlock between PL310 and PCIe. This problem does not affect Armada XP.

**Comment by tpetazzoni** [comment] 2015-06-10 08:20
@gclement In my opinion, it's an issue that will never be fixed. So instead of keeping an issue opened forever, I'd prefer to close it, and reopen it later if Marvell ever finds a fix for it which I believe is quite unlikely.

**Comment by stsp** [comment] 2015-06-10 09:59
Thanks for info.
Then the bug 64 needs a separate explanation.
Hope you can reproduce it.

**Comment by tpetazzoni** [comment] 2015-06-12 19:25
Non-working cpuidle on Armada 38x is currently a hardware issue, for which we're waiting for a proposed workaround. There's no point in keeping a bug tracker entry opened for that.

**Closed by tpetazzoni** 2015-06-12 19:25 UTC
